# SPDX-License-Identifier: GPL-2.0-only
# Generated by tools/nb4-generate-qualified-profile.py. Do not hand edit.
set(NB4_RF_QUALIFIED TRUE)
set(NB4_RF_QUALIFIED_CANDIDATE "USART6")
set(NB4_RF_QUALIFIED_FRAMING "ADDRESSLESS_SLIP")
