/* Copyright (C) Gaston Gelhorn
 * SPDX-License-Identifier: GPL-2.0-only
 */
/* Generated by tools/nb4-generate-qualified-profile.py. Do not hand edit. */
#pragma once

namespace nb4 {

inline constexpr Nb4QualifiedHardwareProfile kNb4QualifiedHardwareProfile = {
  true,
  "NB4-original",
  kNb4RfCandidateUsart6,
  {
    {
      {Nb4RfSharedLine::Pd11, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::Low, 0},
      {Nb4RfSharedLine::Pi8, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::High, 0},
      {},
      {},
      {},
      {},
      {},
      {},
    },
    2,
  },
  {
    {
      {Nb4RfSharedLine::Pd11, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::High, 0},
      {Nb4RfSharedLine::Pi8, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::High, 0},
      {},
      {},
      {},
      {},
      {},
      {},
    },
    2,
  },
  {
    {
      {Nb4RfSharedLine::Pd11, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::Low, 0},
      {Nb4RfSharedLine::Pi8, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::High, 0},
      {},
      {},
      {},
      {},
      {},
      {},
    },
    2,
  },
  {
    {
      {Nb4RfSharedLine::Pd11, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::Low, 0},
      {Nb4RfSharedLine::Pi8, Nb4RfPinMode::OutputPushPull, Nb4RfLevel::High, 0},
      {},
      {},
      {},
      {},
      {},
      {},
    },
    2,
  },
  {Nb4RfFraming::AddresslessSlip, 0, false, 5000, 30000},
};

}  // namespace nb4
