/*
 * Copyright (C) EdgeTX
 *
 * Based on code named
 *   opentx - https://github.com/opentx/opentx
 *   th9x - http://code.google.com/p/th9x
 *   er9x - http://code.google.com/p/er9x
 *   gruvin9x - http://code.google.com/p/gruvin9x
 *
 * License GPLv2: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

// This file is auto-generated via cfn_sorter.sh. Do not edit.

#include "dataconstants.h"

Functions cfn_sorted[] = {
#if defined(TRANSLATIONS_CN)
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_VALUE,
  FUNC_PLAY_TRACK,
  FUNC_RANGECHECK,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_RESET,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_LOGS,
  FUNC_TRAINER,
  FUNC_SCREENSHOT,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_RACING_MODE,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BIND,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_ADJUST_GVAR,
  FUNC_SET_SCREEN,
  FUNC_INSTANT_TRIM,
  FUNC_VOLUME,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_HAPTIC,
  FUNC_PLAY_SCRIPT,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RGB_LED,
  FUNC_VARIO,
#elif defined(TRANSLATIONS_CZ)
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_VOLUME,
  FUNC_PLAY_VALUE,
  FUNC_PLAY_SOUND,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_INSTANT_TRIM,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_RANGECHECK,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_LOGS,
  FUNC_PLAY_SCRIPT,
  FUNC_BIND,
  FUNC_ADJUST_GVAR,
  FUNC_SET_FAILSAFE,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_PLAY_TRACK,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RESET,
  FUNC_RGB_LED,
  FUNC_SCREENSHOT,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_VARIO,
  FUNC_HAPTIC,
  FUNC_SET_SCREEN,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_RACING_MODE,
  FUNC_SET_TIMER,
#elif defined(TRANSLATIONS_DA)
  FUNC_RANGECHECK,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_VARIO,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_INSTANT_TRIM,
  FUNC_ADJUST_GVAR,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_VOLUME,
  FUNC_BIND,
  FUNC_RESET,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_RGB_LED,
  FUNC_RACING_MODE,
  FUNC_LOGS,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_SCREENSHOT,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
#if defined(DEBUG)
  FUNC_TEST,
#endif
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_TRAINER,
  FUNC_HAPTIC,
  FUNC_SET_SCREEN,
#elif defined(TRANSLATIONS_DE)
  FUNC_ADJUST_GVAR,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_PLAY_TRACK,
  FUNC_HAPTIC,
  FUNC_SET_SCREEN,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_INSTANT_TRIM,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_VOLUME,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_TRAINER,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_BIND,
  FUNC_RACING_MODE,
  FUNC_RANGECHECK,
  FUNC_RGB_LED,
  FUNC_RESET,
  FUNC_SCREENSHOT,
  FUNC_LOGS,
  FUNC_SET_FAILSAFE,
  FUNC_SET_TIMER,
  FUNC_PLAY_SOUND,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_OVERRIDE_CHANNEL,
  FUNC_VARIO,
  FUNC_PLAY_VALUE,
#elif defined(TRANSLATIONS_ES)
  FUNC_SET_TIMER,
  FUNC_ADJUST_GVAR,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_SCREENSHOT,
  FUNC_RANGECHECK,
  FUNC_BIND,
  FUNC_TRAINER,
  FUNC_SET_FAILSAFE,
  FUNC_HAPTIC,
  FUNC_INSTANT_TRIM,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_PLAY_TRACK,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_VALUE,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_RESET,
  FUNC_RGB_LED,
  FUNC_LOGS,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_SET_SCREEN,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_VARIO,
  FUNC_VOLUME,
#elif defined(TRANSLATIONS_FI)
  FUNC_ADJUST_GVAR,
  FUNC_DISABLE_AUDIO_AMP,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_HAPTIC,
  FUNC_INSTANT_TRIM,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_BIND,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_RANGECHECK,
  FUNC_RESET,
  FUNC_RGB_LED,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_SCREENSHOT,
  FUNC_LOGS,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_SET_SCREEN,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_VARIO,
  FUNC_VOLUME,
#elif defined(TRANSLATIONS_FR)
  FUNC_ADJUST_GVAR,
  FUNC_BIND,
  FUNC_SET_TIMER,
  FUNC_SET_SCREEN,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_TRAINER,
  FUNC_INSTANT_TRIM,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_SOUND,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_VALUE,
  FUNC_LOGS,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_SCREENSHOT,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_SET_FAILSAFE,
  FUNC_RESET,
  FUNC_OVERRIDE_CHANNEL,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_RGB_LED,
  FUNC_PLAY_SCRIPT,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_RANGECHECK,
  FUNC_VARIO,
  FUNC_HAPTIC,
  FUNC_VOLUME,
#elif defined(TRANSLATIONS_HE)
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_HAPTIC,
  FUNC_INSTANT_TRIM,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_BIND,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RANGECHECK,
  FUNC_RGB_LED,
  FUNC_LOGS,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_VARIO,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_RESET,
#if defined(DEBUG)
  FUNC_TEST,
#endif
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_SET_SCREEN,
  FUNC_PLAY_SOUND,
  FUNC_ADJUST_GVAR,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_TRAINER,
  FUNC_RACING_MODE,
  FUNC_VOLUME,
  FUNC_SCREENSHOT,
#elif defined(TRANSLATIONS_IT)
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_RESET,
  FUNC_BIND,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_OVERRIDE_CHANNEL,
  FUNC_INSTANT_TRIM,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_RGB_LED,
  FUNC_PLAY_VALUE,
  FUNC_LOGS,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_TRAINER,
  FUNC_RACING_MODE,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RANGECHECK,
  FUNC_ADJUST_GVAR,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_SCREENSHOT,
  FUNC_PLAY_SCRIPT,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_SET_SCREEN,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_VARIO,
  FUNC_HAPTIC,
  FUNC_VOLUME,
#elif defined(TRANSLATIONS_JP)
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_BACKGND_MUSIC,
  FUNC_SET_FAILSAFE,
  FUNC_ADJUST_GVAR,
  FUNC_INSTANT_TRIM,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RGB_LED,
  FUNC_LOGS,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_PLAY_SOUND,
  FUNC_VOLUME,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_HAPTIC,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_VARIO,
  FUNC_SET_SCREEN,
  FUNC_BIND,
  FUNC_RESET,
  FUNC_RACING_MODE,
  FUNC_RANGECHECK,
  FUNC_PLAY_TRACK,
  FUNC_SCREENSHOT,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_PLAY_VALUE,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_SET_TIMER,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
#elif defined(TRANSLATIONS_KO)
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_RGB_LED,
  FUNC_LOGS,
  FUNC_PLAY_VALUE,
  FUNC_RANGECHECK,
  FUNC_RACING_MODE,
  FUNC_SET_SCREEN,
  FUNC_BIND,
  FUNC_VARIO,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_VOLUME,
  FUNC_PLAY_SOUND,
  FUNC_SCREENSHOT,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_ADJUST_GVAR,
  FUNC_INSTANT_TRIM,
  FUNC_HAPTIC,
  FUNC_RESET,
  FUNC_OVERRIDE_CHANNEL,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_SET_TIMER,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_PLAY_TRACK,
  FUNC_TRAINER,
  FUNC_SET_FAILSAFE,
#elif defined(TRANSLATIONS_NL)
  FUNC_DISABLE_AUDIO_AMP,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_PLAY_SOUND,
  FUNC_HAPTIC,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_INSTANT_TRIM,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_BIND,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_OVERRIDE_CHANNEL,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_RANGECHECK,
  FUNC_RESET,
  FUNC_RGB_LED,
  FUNC_SCREENSHOT,
  FUNC_LOGS,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_SET_SCREEN,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_VARIO,
  FUNC_VOLUME,
  FUNC_ADJUST_GVAR,
#elif defined(TRANSLATIONS_PL)
  FUNC_OVERRIDE_CHANNEL,
  FUNC_VOLUME,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
  FUNC_INSTANT_TRIM,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_LOGS,
  FUNC_BIND,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_RANGECHECK,
  FUNC_RESET,
  FUNC_RGB_LED,
  FUNC_SET_SCREEN,
  FUNC_SET_FAILSAFE,
  FUNC_PLAY_SCRIPT,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_ADJUST_GVAR,
  FUNC_SET_TIMER,
  FUNC_VARIO,
  FUNC_HAPTIC,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_SCREENSHOT,
#elif defined(TRANSLATIONS_PT)
  FUNC_ADJUST_GVAR,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_BIND,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_SCREENSHOT,
  FUNC_SET_FAILSAFE,
  FUNC_SET_TIMER,
  FUNC_SET_SCREEN,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_RGB_LED,
  FUNC_LOGS,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_RACING_MODE,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RANGECHECK,
  FUNC_PLAY_VALUE,
  FUNC_RESET,
  FUNC_PLAY_SCRIPT,
  FUNC_OVERRIDE_CHANNEL,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_TRAINER,
  FUNC_INSTANT_TRIM,
  FUNC_VARIO,
  FUNC_HAPTIC,
  FUNC_VOLUME,
#elif defined(TRANSLATIONS_RU)
  FUNC_BIND,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_PLAY_VALUE,
  FUNC_RGB_LED,
  FUNC_LOGS,
  FUNC_SET_FAILSAFE,
  FUNC_VARIO,
  FUNC_HAPTIC,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_SET_SCREEN,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_VOLUME,
  FUNC_INSTANT_TRIM,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_BACKGND_MUSIC,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_ADJUST_GVAR,
  FUNC_OVERRIDE_CHANNEL,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_RANGECHECK,
  FUNC_RACING_MODE,
  FUNC_RESET,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_SCREENSHOT,
  FUNC_TRAINER,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_SET_TIMER,
#elif defined(TRANSLATIONS_SE)
  FUNC_DISABLE_AUDIO_AMP,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_HAPTIC,
  FUNC_ADJUST_GVAR,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_LOGS,
  FUNC_PLAY_SCRIPT,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_TRAINER,
  FUNC_BACKGND_MUSIC,
  FUNC_BIND,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_RANGECHECK,
  FUNC_RGB_LED,
  FUNC_SCREENSHOT,
  FUNC_INSTANT_TRIM,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_SET_SCREEN,
#if defined(DEBUG)
  FUNC_TEST,
#endif
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_VARIO,
  FUNC_VOLUME,
  FUNC_RESET,
#elif defined(TRANSLATIONS_TW)
  FUNC_PLAY_SCRIPT,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RGB_LED,
  FUNC_VARIO,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_ADJUST_GVAR,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_SCREENSHOT,
  FUNC_HAPTIC,
  FUNC_INSTANT_TRIM,
  FUNC_PLAY_VALUE,
  FUNC_PLAY_SOUND,
  FUNC_BACKGND_MUSIC,
  FUNC_PLAY_TRACK,
  FUNC_TRAINER,
  FUNC_BACKGND_MUSIC_PAUSE,
  FUNC_BIND,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_RANGECHECK,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_RACING_MODE,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_LOGS,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_SET_SCREEN,
  FUNC_RESET,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_VOLUME,
#elif defined(TRANSLATIONS_UA)
  FUNC_SET_FAILSAFE,
  FUNC_VARIO,
  FUNC_SET_SCREEN,
  FUNC_HAPTIC,
  FUNC_SET_TIMER,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_VALUE,
  FUNC_PLAY_TRACK,
  FUNC_VOLUME,
  FUNC_INSTANT_TRIM,
  FUNC_BIND,
  FUNC_ADJUST_GVAR,
  FUNC_OVERRIDE_CHANNEL,
  FUNC_RANGECHECK,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_DISABLE_AUDIO_AMP,
  FUNC_RACING_MODE,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_RESET,
  FUNC_SCREENSHOT,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RGB_LED,
  FUNC_LOGS,
#else
  FUNC_ADJUST_GVAR,
  FUNC_DISABLE_AUDIO_AMP,
#if !defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_BACKGND_MUSIC,
  FUNC_BACKGND_MUSIC_PAUSE,
#if defined(OLED_SCREEN)
  FUNC_BACKLIGHT,
#endif
  FUNC_HAPTIC,
  FUNC_INSTANT_TRIM,
#if defined(VIDEO_SWITCH)
  FUNC_LCD_TO_VIDEO,
#endif
  FUNC_PLAY_SCRIPT,
  FUNC_BIND,
#if defined(COLORLCD)
  FUNC_DISABLE_TOUCH,
#endif
  FUNC_OVERRIDE_CHANNEL,
  FUNC_PLAY_SOUND,
  FUNC_PLAY_TRACK,
  FUNC_PLAY_VALUE,
#if defined(FUNCTION_SWITCHES)
  FUNC_PUSH_CUST_SWITCH,
#endif
  FUNC_RACING_MODE,
  FUNC_RANGECHECK,
  FUNC_RESET,
  FUNC_RGB_LED,
  FUNC_SCREENSHOT,
  FUNC_LOGS,
  FUNC_SET_TIMER,
  FUNC_SET_FAILSAFE,
  FUNC_SET_SCREEN,
#if defined(DEBUG)
  FUNC_TEST,
#endif
  FUNC_TRAINER,
  FUNC_VARIO,
  FUNC_VOLUME,
#endif
};

uint8_t getFuncSortIdx(uint8_t func)
{
  for (uint8_t i = 0; i < FUNC_MAX; i += 1)
    if (cfn_sorted[i] == func)
      return i;
  return 0;
}
